//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraclassWorks
    {
        public int Id { get; set; }
        public double Percentage { get; set; }
        public string Name { get; set; }
    
        public virtual RegisterProfiles RegisterProfiles { get; set; }
    }
}
