//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterProfiles()
        {
            this.ExamScores = new HashSet<ExamScores>();
            this.ExtraclassWorksScores = new HashSet<ExtraclassWorksScores>();
            this.Scores = new HashSet<Scores>();
            this.Exams = new HashSet<Exams>();
            this.ExtraclassWorks = new HashSet<ExtraclassWorks>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double DailyWorkPercentage { get; set; }
        public double AssistancePercentage { get; set; }
        public int YearCreated { get; set; }
        public int NumberOfLessons { get; set; }
        public int TrimesterId { get; set; }
        public int SchoolYearId { get; set; }
        public int SubjectId { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamScores> ExamScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraclassWorksScores> ExtraclassWorksScores { get; set; }
        public virtual SchoolYears SchoolYears { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Trimesters Trimesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scores> Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraclassWorks> ExtraclassWorks { get; set; }
        public virtual Users Users { get; set; }
    }
}
