//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scores()
        {
            this.ExamScores = new HashSet<ExamScores>();
            this.ExtraclassWorksScores = new HashSet<ExtraclassWorksScores>();
        }
    
        public int Id { get; set; }
        public double DailyWorkPercentage { get; set; }
        public double ConceptPercentage { get; set; }
        public double AssistancePercentage { get; set; }
        public int Belated { get; set; }
        public int Absences { get; set; }
        public int YearCreated { get; set; }
        public double DailyWorkScore { get; set; }
    
        public virtual RegisterProfiles RegisterProfiles { get; set; }
        public virtual Students Students { get; set; }
        public virtual Classes Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamScores> ExamScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraclassWorksScores> ExtraclassWorksScores { get; set; }
    }
}
