//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public Nullable<double> DailyWorkPercentage { get; set; }
        public Nullable<double> ConceptPercentage { get; set; }
        public Nullable<double> AssistancePercentage { get; set; }
        public Nullable<int> Belated { get; set; }
        public Nullable<int> Absences { get; set; }
    
        public virtual RegisterProfiles RegisterProfiles { get; set; }
        public virtual Students Students { get; set; }
    }
}
